version: "3"

tasks:
  up:
    desc: Build and start containers in detached mode
    cmd: docker compose up -d --build

  down:
    desc: Stop and remove containers
    cmd: docker compose down

  stop:
    desc: Stop containers without removing them
    cmd: docker compose stop

  logs:
    desc: Follow the app container logs
    cmd: docker compose logs -f app

  restart:
    desc: Restart the app container
    cmd: docker compose restart app

  lock:
    desc: Regenerate uv.lock from pyproject.toml
    cmd: docker compose exec app uv lock

  add:
    desc: "Add a package (usage: task add -- <package>)"
    cmd: docker compose exec app uv add {{.CLI_ARGS}}

  remove:
    desc: "Remove a package (usage: task remove -- <package>)"
    cmd: docker compose exec app uv remove {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmd: docker compose exec app pytest tests/ -v

  test-file:
    desc: "Run a specific test file (usage: task test-file -- tests/routers/test_auth.py)"
    cmd: docker compose exec app pytest {{.CLI_ARGS}} -v

  create-admin:
    desc: "Create an admin user (usage: task create-admin)"
    cmd: docker compose exec app python -m app.cli.create_admin

  migrate:
    desc: Run database migrations
    cmd: docker compose exec app alembic upgrade head

  migration:
    desc: "Create a new migration (usage: task migration -- 'description')"
    cmd: docker compose exec app alembic revision --autogenerate -m "{{.CLI_ARGS}}"
